// List of emotions to detect and their corresponding keywords
export const emotions = {
  hello: [
    "hello",
    "hi",
    "hey",
    "howdy",
    "greetings",
    "good morning",
    "good afternoon",
    "good evening",
    "good night",
    "good day",
    "good day to you",
    "good day to you too",
  ],
  bye: [
    "bye",
    "goodbye",
    "see you later",
    "take care",
    "see ya",
    "tata",
    "i'll catch you later",
    "laters",
    "toddles",
    "sayonara",
  ],
  excited: [
    "excited",
    "can't wait",
    "awesome",
    "super",
    "supereb",
    "amazing",
    "fantastic",
    "great",
    "wonderful",
    "incredible",
    "unbelievable",
    "marvelous",
    "fabulous",
    "terrific",
    "tremendous",
    "stupendous",
    "phenomenal",
    "extraordinary",
    "remarkable",
    "exceptional",
    "astonishing",
    "astounding",
    "incredible",
    "unbelievable",
    "magnificent",
    "glorious",
    "majestic",
    "grand",
    "impressive",
    "stunning",
    "breathtaking",
    "awe-inspiring",
    "exquisite",
    "remarkable",
    "splendid",
    "magnificent",
    "superb",
    "outstanding",
    "exceptional",
    "first-rate",
    "first-class",
    "of the highest quality",
    "of the highest standard",
    "of the first water",
    "of the first order",
    "par excellence",
    "without equal",
    "unparalleled",
    "unrivaled",
    "peerless",
    "matchless",
    "unequaled",
    "unsurpassed",
    "unexcelled",
    "second to none",
    "in a class of its own",
    "incomparable",
    "inimitable",
    "nonpareil",
    "unexampled",
    "unprecedented",
    "unheard of",
    "unique",
    "rare",
    "scarcely believable",
    "hard to swallow",
    "hard to believe",
    "beyond belief",
    "inconceivable",
    "unimaginable",
    "impossible",
    "incredible",
    "unbelievable",
    "unthinkable",
    "unthought of",
    "unheard of",
    "undreamed of",
    "fantastic",
    "marvelous",
    "wonderful",
    "amazing",
    "astonishing",
    "astounding",
    "extraordinary",
    "remarkable",
    "unusual",
    "surprising",
    "breathtaking",
    "staggering",
    "incredible",
    "mind-blowing",
    "mind-boggling",
    "jaw-dropping",
    "awe-inspiring",
    "phenomenal",
    "prodigious",
    "miraculous",
    "stupendous",
    "fantabulous",
    "out of this world",
    "out of the ordinary",
    "out of the way",
    "out of sight",
    "out of the question",
    "out of the blue",
    "out of the running",
    "out of the running for",
    "out of the running for something",
  ],
  ashamed: [
    "ashamed",
    "guilty",
    "embarrassed",
    "sorry",
    "regretful",
    "remorseful",
    "contrite",
    "repentant",
    "penitent",
    "ashamed of yourself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of yourself",
    "ashamed of themselves",
    "ashamed of herself",
    "ashamed of himself",
    "ashamed of myself",
    "ashamed of oneself",
    "ashamed of myself",
    "ashamed of himself",
    "ashamed of herself",
    "ashamed of themselves",
    "ashamed of ourselves",
    "ashamed of",
  ],
  calm: [
    "calm",
    "relaxed",
    "serene",
    "peaceful",
    "tranquil",
    "placid",
    "untroubled",
    "unperturbed",
    "unruffled",
    "unflustered",
    "unagitated",
    "unexcited",
    "undisturbed",
    "unworried",
    "unruffled",
    "unflappable",
    "unshaken",
    "unperturbed",
    "untroubled",
    "unflustered",
    "unagitated",
    "unruffled",
    "chill",
    "cool",
    "meditate",
    "yoga",
  ],
  joy: [
    "joy",
    "happy",
    "great",
    "joyful",
    "happy",
    "pleased",
    "delighted",
    "smiling",
    "cheerful",
    "cheery",
    "merry",
    "jovial",
    "jolly",
    "jocular",
    "gleeful",
    "carefree",
    "untroubled",
    "content",
    "contented",
    "satisfied",
    "gratified",
    "buoyant",
    "radiant",
    "sunny",
    "blithe",
    "joyous",
    "beatific",
    "blissful",
    "euphoric",
    "ecstatic",
    "exultant",
    "elated",
    "rapturous",
    "in seventh heaven",
    "on cloud nine",
    "over the moon",
    "walking on air",
    "in high spirits",
    "in good spirits",
  ],
  love: [
    "love",
    "I love you",
    "I adore you",
    "i am there for you",
    "i am with you",
    "i am always with you",
    "with you forever",
    "jaan",
    "baby",
    "babes",
    "sweetheart",
    "sweetie",
    "darling",
    "dear",
    "dearest",
    "honey",
    "beloved",
    "love",
    "loved",
    "loving",
    "in love",
  ],
  sad: [
    "sad",
    "down",
    "hopeless",
    "depressed",
    "unhappy",
    "sorrowful",
    "sorrow",
    "mournful",
    "mourn",
    "grief",
    "grieve",
    "grieving",
    "grieved",
    "heartbroken",
    "heartbreak",
    "broken heart",
    "brokenhearted",
    "tearful",
    "weeping",
    "crying",
    "sobbing",
    "sob",
    "weep",
    "weepy",
    "teary",
    "tearful",
    "lachrymose",
    "miserable",
    "wretched",
    "woeful",
    "forlorn",
    "crestfallen",
    "despondent",
    "disconsolate",
    "despairing",
    "distraught",
    "downcast",
    "dejected",
    "downhearted",
    "down in the dumps",
    "down in the mouth",
    "low-spirited",
    "heavy-hearted",
    "sad-hearted",
    "heavyhearted",
    "sadhearted",
    "broken-hearted",
    "brokenhearted",
    "heart-sick",
    "heartsick",
    "heart-sore",
    "heartsore",
  ],
  irritated: [
    "irritated",
    "annoyed",
    "frustrated",
    "irritating",
    "annoying",
    "frustrating",
    "get lost",
  ],
  angry: [
    "angry",
    "mad",
    "furious",
    "get lost",
    "get out",
    "get out of here",
    "get out of my way",
    "get out of my sight",
    "get out of my face",
    "get out of my life",
    "get out of my room",
    "get out of my house",
    " i dont want to talk",
    "breakup",
    "break up",
    "shut up",
    "you are idiot",
  ],
  bored: [
    "bored",
    "tired",
    "sick of",
    "fed up",
    "boredom",
    "tiredness",
    "sick of it",
    "fed up with",
  ],
  curious: [
    "curious",
    "interested",
    "want to know",
    "want to learn",
    "want to understand",
    "want to find out",
    "want to discover",
    "want to explore",
    "want to investigate",
    "want to know more",
    "want to learn more",
    "want to understand more",
    "want to find out more",
    "want to discover more",
    "want to explore more",
    "want to investigate more",
    "want to know everything",
    "want to learn everything",
    "want to understand everything",
    "want to find out everything",
    "want to discover everything",
    "want to explore everything",
    "want to investigate everything",
    "want to know all",
    "want to learn all",
    "want to understand all",
    "want to find out all",
    "want to discover all",
    "want to explore all",
    "want to investigate all",
    "want to know the truth",
    "want to learn the truth",
    "want to understand the truth",
    "want to find out the truth",
    "want to discover the truth",
    "want to explore the truth",
    "want to investigate the truth",
    "want to know the answer",
    "want to learn the answer",
    "want to understand the answer",
    "want to find out the answer",
    "want to discover the answer",
    "want to explore the answer",
    "want to investigate the answer",
    "want to know the facts",
    "want to learn the facts",
    "want to understand the facts",
    "want to find out the facts",
    "want to discover the facts",
    "want to explore the facts",
    "want to investigate the facts",
    "want to know the details",
    "want to learn the details",
    "want to understand the details",
    "want to find out the details",
    "want to discover the details",
    "want to explore the details",
    "want to investigate the details",
    "want to know the information",
    "want to learn the information",
    "want to understand the information",
    "want to find out the information",
    "want to discover the information",
    "want to explore the information",
    "want to investigate the information",
    "want to know the news",
    "want to learn the news",
    "want to understand the news",
    "want to find out the news",
    "want to discover the news",
    "want to explore the news",
    "want to investigate the news",
    "want to know the story",
    "want to learn the story",
    "want to understand the story",
    "want to find out the story",
    "want to discover the story",
    "want to explore the story",
    "want to investigate the story",
    "want to know the truth",
    "want to learn the truth",
    "want to understand the truth",
  ],
  blank: [
    "don't know",
    "not sure",
    "sorry",
    "why",
    "what",
    "how",
    "where",
    "when",
  ],
};
